[project]
name = "batman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AbhisekRao16", email = "abhisekrao1608@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyaudio>=0.2.14",
    "pyttsx3>=2.99",
    "speechrecognition>=3.17.0",
]

[project.scripts]
batman = "batman:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
